python pydoc_markdown.py resources "resources.py"
python pydoc_markdown.py att "att.py"
python pydoc_markdown.py factory "factory.py"
python pydoc_markdown.py iotApplication "iotApplication.py"
python pydoc_markdown.py nw_watchdog "nw_watchdog.py"
python pydoc_markdown.py timer "timer.py"
python pydoc_markdown.py when "when.py"
python pydoc_markdown.py when_platform "when_platform.py"